import { ListOfCourses } from '../models/listOfCourses.interface';

export const listOfCourses: ListOfCourses[] = [
  {
    id: 1,
    title: 'How to drum',
    categories: 'Music',
    description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Beginner',
  },
  {
    id: 2,
    title: 'How to drum',
    categories: 'Music',
    description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Intermediate',
  },
  {
    id: 3,
    title: 'How to drum',
    categories: 'Music',
    description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Advanced',
  },
  {
    id: 4,
    title: 'How to sing',
    categories: 'Music',
    description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Beginner',
  },
  {
    id: 5,
    title: 'How to sing',
    categories: 'Music',
    description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Intermediate',
  },
  {
    id: 6,
    title: 'How to sing',
    categories: 'Music',
    description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Advanced',
  },
  {
    id: 7,
    title: 'How to make electronic music',
    categories: 'Music',
    description: 'Learn to make electronic music with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Beginner',
  },
  {
    id: 8,
    title: 'How make electronic music',
    categories: 'Music',
    description: 'Learn to make electronic music with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Intermediate',
  },
  {
    id: 9,
    title: 'How to make electronic music',
    categories: 'Music',
    description: 'Learn to make electronic music with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/music.jpg',
    level: 'Advanced',
  },
  {
    id: 10,
    title: 'Learn JavaScript',
    categories: 'Coding',
    description: 'Learn JavaScript with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Beginner',
  },
  {
    id: 11,
    title: 'Learn JavaScript',
    categories: 'Coding',
    description: 'Learn JS with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Intermediate',
  },
  {
    id: 12,
    title: 'Learn JavaScrip',
    categories: 'Coding',
    description: 'Learn JS with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Advanced',
  },
  {
    id: 13,
    title: 'Learn Go',
    categories: 'Coding',
    description: 'Learn Go with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Beginner',
  },
  {
    id: 14,
    title: 'Learn Go',
    categories: 'Coding',
    description: 'Learn Go with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Intermediate',
  },
  {
    id: 15,
    title: 'Learn Go',
    categories: 'Coding',
    description: 'Learn Go with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Advanced',
  },
  {
    id: 16,
    title: 'Learn C Sharp',
    categories: 'Coding',
    description: 'Learn C Sharp with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Beginner',
  },
  {
    id: 17,
    title: 'Learn C Sharp',
    categories: 'Coding',
    description: 'Learn C Sharp online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Intermediate',
  },
  {
    id: 18,
    title: 'Learn C Sharp',
    categories: 'Coding',
    description: 'Learn C Sharp online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/dev.jpg',
    level: 'Advanced',
  },
  {
    id: 19,
    title: 'Graphic Design',
    categories: 'Design',
    description: 'Learn Graphic Design with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Beginner',
  },
  {
    id: 20,
    title: 'Graphic Design',
    categories: 'Design',
    description: 'Learn Graphic Design with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Intermediate',
  },
  {
    id: 21,
    title: 'Graphic Design',
    categories: 'Design',
    description: 'Learn Graphic Design with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Advanced',
  },
  {
    id: 22,
    title: 'Game Design',
    categories: 'Design',
    description: 'Learn Game Design online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Beginner',
  },
  {
    id: 23,
    title: 'Game Design',
    categories: 'Design',
    description: 'Learn Game Design online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Intermediate',
  },
  {
    id: 24,
    title: 'Game Design',
    categories: 'Design',
    description: 'Learn Game Design online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Advanced',
  },
  {
    id: 25,
    title: 'Google UX Design',
    categories: 'Design',
    description: 'Learn Google UX Design with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Beginner',
  },
  {
    id: 26,
    title: 'Google UX Design',
    categories: 'Design',
    description: 'Learn Google UX Design with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Intermediate',
  },
  {
    id: 27,
    title: 'Google UX Design',
    categories: 'Design',
    description: 'Learn Google UX Design with online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/design.jpg',
    level: 'Advanced',
  },
  {
    id: 28,
    title: 'Database Engineer',
    categories: 'Engineer',
    description: 'Learn Database Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Beginner',
  },
  {
    id: 29,
    title: 'Database Engineer',
    categories: 'Engineer',
    description: 'Learn Database Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Intermediate',
  },
  {
    id: 30,
    title: 'Database Engineer',
    categories: 'Engineer',
    description: 'Learn Database Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Advanced',
  },
  {
    id: 31,
    title: 'DevOps Engineer',
    categories: 'Engineer',
    description: 'Learn DevOps Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Beginner',
  },
  {
    id: 32,
    title: 'DevOps Engineer',
    categories: 'Engineer',
    description: 'Learn DevOps Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Intermediate',
  },
  {
    id: 33,
    title: 'DevOps Engineer',
    categories: 'Engineer',
    description: 'Learn DevOps Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Advanced',
  },
  {
    id: 34,
    title: 'Network Engineer',
    categories: 'Engineer',
    description: 'Learn Network Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Beginner',
  },
  {
    id: 35,
    title: 'Network Engineer',
    categories: 'Engineer',
    description: 'Learn Network Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Intermediate',
  },
  {
    id: 36,
    title: 'Network Engineer',
    categories: 'Engineer',
    description: 'Learn Network Engineering online courses that offer comprehensive instruction and personalized feedback.',
    img: './assets/img/it.jpg',
    level: 'Advanced',
  },
  {
    id: 37,
    title: 'How to master your brain',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Beginner',
  },
  {
    id: 28,
    title: 'How to master your brain',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Intermediate',
  },
  {
    id: 39,
    title: 'How to master your brain',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Advanced',
  },
  {
    id: 40,
    title: 'How to master your body',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Beginner',
  },
  {
    id: 41,
    title: 'How to master your body',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Intermediate',
  },
  {
    id: 42,
    title: 'How to master your body',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Advanced',
  },
  {
    id: 43,
    title: 'How to master your mental',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Beginner',
  },
  {
    id: 44,
    title: 'How to master your mental',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Intermediate',
  },
  {
    id: 45,
    title: 'How to master your mental',
    categories: 'Psychology',
    description: 'The NBA (or Neurocognitive and Behavioral Approach) is a fascinating, innovative and multi-disciplinary approach, developed by the French scientist J. Fradin. ',
    img: './assets/img/pers.jpg',
    level: 'Advanced',
  },
  {
    id: 46,
    title: 'How to Finance',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Beginner',
  },
  {
    id: 47,
    title: 'How to Finance',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Intermediate',
  },
  {
    id: 48,
    title: 'How to Finance',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Advanced',
  },
  {
    id: 49,
    title: 'How to Budget and Forecast ',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Beginner',
  },
  {
    id: 50,
    title: 'How to Budget and Forecast ',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Intermediate',
  },
  {
    id: 51,
    title: 'How to Budget and Forecast ',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Advanced',
  },
  {
    id: 52,
    title: 'People Management',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Beginner',
  },
  {
    id: 53,
    title: 'People Management',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Intermediate',
  },
  {
    id: 54,
    title: 'People Management',
    categories: 'Business',
    description: 'Boost your business skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/bu.jpg',
    level: 'Advanced',
  },
  {
    id: 55,
    title: 'Digital Finance and Banking',
    categories: 'Finance',
    description: 'Boost your finance skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/board.jpg',
    level: 'Beginner',
  },
  {
    id: 56,
    title: 'Digital Finance and Banking',
    categories: 'Finance',
    description: 'Boost your finance skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/board.jpg',
    level: 'Intermediate',
  },
  {
    id: 57,
    title: 'Digital Finance and Banking',
    categories: 'Finance',
    description: 'Boost your finance skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/board.jpg',
    level: 'Advanced',
  },
  {
    id: 58,
    title: 'MBA-FinTech',
    categories: 'Finance',
    description: 'Boost your finance skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/board.jpg',
    level: 'Beginner',
  },
  {
    id: 59,
    title: 'MBA-FinTech',
    categories: 'Finance',
    description: 'Boost your finance skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/board.jpg',
    level: 'Intermediate',
  },
  {
    id: 60,
    title: 'MBA-FinTech',
    categories: 'Finance',
    description: 'Boost your finance skills with online courses that provide practical knowledge and strategies for success.',
    img: './assets/img/board.jpg',
    level: 'Advanced',
  },
  // {
  //   id: 1,
  //   title: 'How to drum',
  //   categories: 'Music',
  //   description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Beginner',
  // },
  // {
  //   id: 2,
  //   title: 'How to drum',
  //   categories: 'Music',
  //   description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Intermediate',
  // },
  // {
  //   id: 3,
  //   title: 'How to drum',
  //   categories: 'Music',
  //   description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Advanced',
  // },
  // {
  //   id: 4,
  //   title: 'How to sing',
  //   categories: 'Music',
  //   description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Beginner',
  // },
  // {
  //   id: 5,
  //   title: 'How to sing',
  //   categories: 'Music',
  //   description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Intermediate',
  // },
  // {
  //   id: 6,
  //   title: 'How to sing',
  //   categories: 'Music',
  //   description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Advanced',
  // },
  // {
  //   id: 1,
  //   title: 'How to drum',
  //   categories: 'Music',
  //   description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Beginner',
  // },
  // {
  //   id: 2,
  //   title: 'How to drum',
  //   categories: 'Music',
  //   description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Intermediate',
  // },
  // {
  //   id: 3,
  //   title: 'How to drum',
  //   categories: 'Music',
  //   description: 'Learn to play the drums with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Advanced',
  // },
  // {
  //   id: 4,
  //   title: 'How to sing',
  //   categories: 'Music',
  //   description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Beginner',
  // },
  // {
  //   id: 5,
  //   title: 'How to sing',
  //   categories: 'Music',
  //   description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Intermediate',
  // },
  // {
  //   id: 6,
  //   title: 'How to sing',
  //   categories: 'Music',
  //   description: 'Learn to sing with online courses that offer comprehensive instruction and personalized feedback.',
  //   img: './assets/img/music.jpg',
  //   level: 'Advanced',
  // },
];
// Beginner, Intermediate, Advanced

